#!/bin/sh
# Generated by vim-plug
# Thursday 10 December 2015 08:35:13 PM IST

vim +PlugUpdate +qa

PLUG_HOME=~/.config/nvim/bundle

cd $PLUG_HOME/SearchComplete/ && git reset --hard d85ccf8
cd $PLUG_HOME/The-NERD-Commenter/ && git reset --hard 49ad459
cd $PLUG_HOME/YouCompleteMe/ && git reset --hard cc623d4
cd $PLUG_HOME/a.vim/ && git reset --hard 2cbe946
cd $PLUG_HOME/bufexplorer.zip/ && git reset --hard 08b0100
cd $PLUG_HOME/cscope_maps.vim/ && git reset --hard 0201278
cd $PLUG_HOME/delimitMate/ && git reset --hard 8bc47fd
cd $PLUG_HOME/neobundle-vim-recipes/ && git reset --hard 1c3f078
cd $PLUG_HOME/neomru.vim/ && git reset --hard bab3124
cd $PLUG_HOME/nimrod.vim/ && git reset --hard 597cca2
cd $PLUG_HOME/puppet-syntax-vim/ && git reset --hard f36cf69
cd $PLUG_HOME/rainbow_parentheses.vim/ && git reset --hard eb8baa5
cd $PLUG_HOME/salt-vim/ && git reset --hard 5b15d37
cd $PLUG_HOME/syntastic/ && git reset --hard 48736aa
cd $PLUG_HOME/tabular/ && git reset --hard 60f2564
cd $PLUG_HOME/tagbar/ && git reset --hard 7b36c46
cd $PLUG_HOME/ultisnips/ && git reset --hard 5a2dcc5
cd $PLUG_HOME/unite.vim/ && git reset --hard f376de8
cd $PLUG_HOME/vim-airline/ && git reset --hard 14d14cf
cd $PLUG_HOME/vim-ansible-yaml/ && git reset --hard c4c524f
cd $PLUG_HOME/vim-bufferline/ && git reset --hard 57f0e8a
cd $PLUG_HOME/vim-dispatch/ && git reset --hard 69fea41
cd $PLUG_HOME/vim-easymotion/ && git reset --hard a21d447
cd $PLUG_HOME/vim-fugitive/ && git reset --hard d854197
cd $PLUG_HOME/vim-gitgutter/ && git reset --hard 28aea43
cd $PLUG_HOME/vim-go/ && git reset --hard 0aeb07e
cd $PLUG_HOME/vim-protobuf/ && git reset --hard 702421c
cd $PLUG_HOME/vim-sml-coursera/ && git reset --hard f338864
cd $PLUG_HOME/vim-snippets/ && git reset --hard c0040ab
cd $PLUG_HOME/vim-surround/ && git reset --hard 2d05440
cd $PLUG_HOME/vim-thrift/ && git reset --hard 9611283
cd $PLUG_HOME/vim-trailing-whitespace/ && git reset --hard 478b217
cd $PLUG_HOME/vimproc/ && git reset --hard c809cb1

