local trouble = require("trouble")
local mapx = require("mapx")

mapx.group({ silent = true }, function()
	mapx.nnoremap("<leader>xo", function()
		trouble.open()
	end)
	mapx.nnoremap("<leader>xx", function()
		trouble.toggle()
	end)
	mapx.nnoremap("<leader>xw", function()
		trouble.open("workspace_diagnostics")
	end)
	mapx.nnoremap("<leader>xd", function()
		trouble.open("document_diagnostics")
	end)
	mapx.nnoremap("<leader>xl", function()
		trouble.open("loclist")
	end)
	mapx.nnoremap("<leader>xq", function()
		trouble.open("quickfix")
	end)
	mapx.nnoremap("<leader>xr", function()
		trouble.open("lsp_references")
	end)
end)
